aqua/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from aqua import settings
from store.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . views import *

app_name = 'cart'

urlpatterns = [
    path('cart', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('detail/', cart_detail, name='cart_detail'),
]

orders/urls.py
from django.urls import path
from . views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('created/', order_created_view, name='order_created'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, initial=1, widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'min': '1',
    }))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import *
from .cart import *
from .forms import *


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    categories = Category.objects.all()
    cart = Cart(request)
    return render(request, 'detail.html', {'cart': cart, 'categories': categories})

cart/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <h4 class="text-center" style="text-shadow: 0px 2px 2px rgba(0, 0, 0, 0.2);">Ваша корзина</h4>
    <div class="table-responsive">
        <table class="table table-bordered custom-shadow p-3 mb-5 bg-body rounded" style="background-color: #F5F5F5 !important;">
            <thead style="background-color: #F5F5F5;">
                <tr>
                    <th class="col-1">Артикул</th>
                    <th class="col-4">Товар</th>
                    <th class="col-2">Цена</th>
                    <th class="col-2">Количество</th>
                    <th class="col-2">Общая стоимость</th>
                    <th class="col-2">Удалить</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    <tr>
                        <td>{{ item.product.article }}</td>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.price }}</td>
                        <td>
                            <form method="post" action="{% url 'cart:cart_add' item.product.id %}">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" class="form-control" style="border-radius: 0% !important;">
                                    <div class="input-group-append">
                                        <input type="submit" value="Обновить" class="btn btn-custom" style="width: 100px !important; border-radius: 0% !important;">
                                    </div>
                                    <input type="hidden" name="update" value="True">
                                </div>
                            </form>
                        </td>
                        <td>{{ item.total_price }}</td>
                        <td>
                            <a href="{% url 'cart:cart_remove' item.product.id %}" class="developer-info text-danger text-decoration-none"><img src="/media/icons/icons8-remove-48.png" alt="Удалить"></a>

                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-end">
        <p class="developer-info text-dark"><strong>Общая стоимость: </strong>&nbsp;</p>
        <p class="developer-info" style="color: #4B0082;"><strong> {{ cart.get_total_price }} грн</strong></p>
    </div>
    
    <div class="d-flex justify-content-end">
        <a href="{% url 'main' %}" class="btn btn-light custom-shadow p-1 mb-3" style="border-radius: 0% !important;">Продолжить покупки</a>
        <a href="{% url 'orders:order_create' %}" class="btn custom-shadow p-1 mb-3" style="border-radius: 0% !important; background-color: #FF8C00; color: #FFFFFF;">Оформить заказ</a>
    </div>    
{% endblock %}