aqua/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from aqua import settings
from store.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .models import *
from .views import *
from store.admin import *


urlpatterns = [
    #АДМИНКА
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    
    #КОНТЕНТ
    path('', main, name='main'),
    path('about-project/', about_project, name='about_project'),
    path('brands/', brand_list, name='brand_list'),
    path('brands/<int:brand_id>/', brand_detail, name='brand_detail'),
    # path('categories/', category_list, name='category_list'),
    path('categories/<slug:category_slug>/subcategories/', subcategory_list, name='subcategory_list'),
    path('categories/<slug:slug>/', category_detail, name='category_detail'),
    path('subcategories/<slug:slug>/', subcategory_detail, name='subcategory_detail'),
    path('products/<slug:slug>/', product_detail, name='product_detail'),
    path('posts/', post_list, name='post_list'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('feedback/', feedback_view, name='feedback'),
    path('search/', search_results, name='search_results'),

    
    #АДМИН ПАНЕЛЬ
    path('upload_csv/', upload_csv, name='upload_csv'),

    # ПОЛЬЗОВАТЕЛЬ
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('profile/change_password/', change_password, name='change_password'),
    ]

store/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from autoslug import AutoSlugField
from django_ckeditor_5.fields import CKEditor5Field
import random


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок посту")
    content=CKEditor5Field('Зміст посту', config_name='extends')
    pub_date = models.DateTimeField(default=timezone.now, verbose_name="Дата публикації")
    photo = models.ImageField(upload_to='post_photos/', blank=True, null=True, verbose_name="Фотографія")
    photos = models.ManyToManyField('Photo', related_name='photo', verbose_name="Фотографії"),

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Стаття'
        verbose_name_plural = 'Статті'


class FeedbackMessage(models.Model):
    name = models.CharField(max_length=100, verbose_name="Им'я користувача")
    message = models.TextField(verbose_name='Повідомлення')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Створено')
    new = models.BooleanField(default=True, verbose_name='Нове')

    def __str__(self):
        return f"Message from {self.name} at {self.created_at}"
    
    class Meta:
        verbose_name = 'Повідомлення'
        verbose_name_plural = 'Повідомлення'


class Brand(models.Model):
    name = models.CharField(max_length=150, unique=True)
    image = models.ImageField(upload_to='images/', null=True, verbose_name="Зображення")
    country = models.CharField(max_length=100)
    description=CKEditor5Field('Описание', config_name='extends')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name ='Бренд'
        verbose_name_plural = 'Бренди'


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)  
    description=CKEditor5Field('Описание', config_name='extends')
    image = models.ImageField(upload_to='images/', null=True, verbose_name="Зображення")
    slug = AutoSlugField(populate_from='name', unique=True, default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Категорія'
        verbose_name_plural = 'Категорії'


class Subcategory(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Назва підкатегорії")
    description=CKEditor5Field('Описание', config_name='extends')
    image = models.ImageField(upload_to='images/', null=True, verbose_name="Зображення підкатегорії")
    slug = AutoSlugField(populate_from='name', unique=True, default='')
    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories', verbose_name="Батьківська категорія")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Підкатегорія'
        verbose_name_plural = 'Підкатегорії'

            
class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name="Назва")
    description=CKEditor5Field('Описание', config_name='extends')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Ціна")
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name="Бренд")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категорія")
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True, blank=True,verbose_name="Підкатегорія")
    slug = AutoSlugField(populate_from='name', unique=True, default='') 
    article = models.PositiveIntegerField(unique=True, verbose_name="Артикул")

    def __str__(self):
        return f"{self.name} - {self.article}"
    
    
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'


def generate_article():
    return random.randint(100000, 999999)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')


@receiver(pre_save, sender=Product)
def set_article(sender, instance, **kwargs):
    if instance._state.adding:  # Проверка, что это новый товар
        instance.article = generate_article()

@receiver(post_save, sender=FeedbackMessage)
def mark_as_new(sender, instance, created, **kwargs):
    if created:
        instance.new = True
        instance.save()

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import *
from orders.models import *


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100, label="Ваше ім'я")
    message = forms.CharField(widget=forms.Textarea, label="Повідомлення")


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomPasswordChangeForm(PasswordChangeForm):
    pass

class CSVUploadForm(forms.Form):
    csv_file = forms.FileField(label='Выберите CSV-файл')
    
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    class Media:
        js = (
            'https://code.jquery.com/jquery-3.6.0.min.js',
            'https://code.jquery.com/ui/1.12.1/jquery-ui.min.js',
        )
        css = {
            'all': (
                'https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css',
            )
        }
    

store/views.py
import random
import requests
import csv
import tempfile
from decimal import Decimal
from django.core.files.base import ContentFile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, F, ExpressionWrapper, DecimalField, Q
from django.conf import settings
from django.http import JsonResponse
from .models import *
from .forms import *
from cart.forms import *
from orders.models import *


cart_session_id = settings.CART_SESSION_ID

def main(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()
    all_products = list(Product.objects.all())
    num_available_products = len(all_products)
    num_random_products = min(num_available_products, 12)
    latest_posts = Post.objects.order_by('-pub_date')[:3]
    random_products = random.sample(all_products, num_random_products)

    context = {
        'categories': categories,
        'brands': brands,
        'random_products': random_products,
        'latest_posts': latest_posts
    }

    return render(request, 'main.html', context)

def footer_category_list(request):
    categories = Category.objects.all()
    return render(request, 'footer_category_list.html', {'categories': categories})


def brand_list(request):
    brands = Brand.objects.all()
    return render(request, 'brand_list.html', {'brands': brands})


def brand_detail(request, brand_id):
    categories = Category.objects.all()
    brand = get_object_or_404(Brand, id=brand_id)
    products = Product.objects.filter(brand=brand)
    items_per_page = 24
    paginator = Paginator(products, items_per_page)    
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)


    return render(request, 'brand_detail.html', {'brand': brand, 'products': products, 'categories': categories})


def about_project(request):
    categories = Category.objects.all()
    return render(request, 'about_project.html', {'categories': categories})


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category_list.html', {'categories': categories})

def subcategory_list(request, category_slug):
    subcategories = Subcategory.objects.filter(parent_category__slug=category_slug)
    return render(request, 'subcategory_list.html', {'subcategories': subcategories})


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    categories = Category.objects.all()
    products = Product.objects.filter(category=category)
    items_per_page = 24
    paginator = Paginator(products, items_per_page)    
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    
    return render(request, 'category_detail.html', {'category': category, 'categories': categories,'products': products})


def subcategory_detail(request, slug):
    categories = Category.objects.all()
    subcategory = get_object_or_404(Subcategory, slug=slug)
    products = Product.objects.filter(subcategory=subcategory)
    items_per_page = 24
    paginator = Paginator(products, items_per_page)    
    page = request.GET.get('page')
    
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'subcategory_detail.html', {'subcategory': subcategory, 'products': products, 'categories': categories})


def product_detail(request, slug):
    categories = Category.objects.all()
    product = get_object_or_404(Product, slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'product_detail.html', {'product': product, 'categories': categories,'cart_product_form': cart_product_form})


def post_list(request):
    categories = Category.objects.all()
    posts = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(posts, 3) 

    page = request.GET.get('page')
    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        paginated_posts = paginator.page(1)
    except EmptyPage:
        paginated_posts = paginator.page(paginator.num_pages)

    return render(request, 'post_list.html', {'paginated_posts': paginated_posts, 'categories': categories})


def post_detail(request, post_id):
    categories = Category.objects.all()
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'post_detail.html', {'post': post, 'categories': categories})


def feedback_view(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']

            feedback_message = FeedbackMessage(name=name, message=message)
            feedback_message.save()

            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = FeedbackForm()
    return render(request, 'feedback_form.html', {'form': form, 'categories': categories})


def search_results(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    query = request.GET.get('q', '').strip()

    if query:
        products = Product.objects.filter(
            Q(name__iregex=rf'{query}') | Q(article__iregex=rf'{query}')
        )

    items_per_page = 24
    paginator = Paginator(products, items_per_page)    
    page = request.GET.get('page')
    
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'search_results.html', {'products': products, 'query': query, 'categories': categories})


# ПОЛЬЗОВАТЕЛЬ
def register(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserRegistrationForm()
    return render(request, 'register.html', {'form': form, 'categories': categories})


def user_login(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main')  
        else:
            messages.error(request, 'Неправильное имя пользователя или пароль.')
    return render(request, 'login.html', {'categories': categories})


@login_required
def user_logout(request):
    logout(request)
    return redirect('main') 


@login_required
def profile(request):
    categories = Category.objects.all()
    user = request.user
    orders = Order.objects.filter(user=user)
    
    total_order_amount = Decimal('0')
    order_total = Decimal('0')
    for order in orders:
        order_total = order.items.annotate(
                    item_total=ExpressionWrapper(F('product__price') * F('quantity'), 
                    output_field=DecimalField())
                    ).aggregate(total=Sum('item_total'))['total'] or Decimal('0')

        # Добавляем стоимость заказа к total_order_amount
        total_order_amount += order_total

        # Добавляем order_total к каждому заказу
        order.order_total = order_total

    # общая сумма сохраняется в сессии
    request.session['total_order_amount'] = str(total_order_amount)

    context = {'user': user, 
               'orders': orders,
               'order_total': order_total,
               'total_order_amount': total_order_amount,
               'categories': categories}

    return render(request, 'profile.html', context) 


@login_required
def order_detail(request, order_id):
    categories = Category.objects.all()
    order = get_object_or_404(Order, id=order_id, user=request.user)
    order_total = order.items.annotate(
        item_total=ExpressionWrapper(F('product__price') * F('quantity'), output_field=DecimalField())
    ).aggregate(total=Sum('item_total'))['total'] or Decimal('0')

    product_slugs = [item.product.slug for item in order.items.all()]

    
    context = {
        'order': order,
        'order_total': order_total,
        'categories': categories,
        'product_slugs': product_slugs,
    }
    
    return render(request, 'order_detail.html', context)

@login_required
def change_password(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Ваш пароль успешно изменен!')
            return redirect('profile')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'change_password.html', {'form': form, 'categories': categories})


#**************************АДМИН ПАНЕЛЬ**************************

# ЗАГРУЗКА ТОВАРОВ НА САЙТ
def handle_uploaded_file(file):
    temp_file = tempfile.NamedTemporaryFile(delete=False)
    for chunk in file.chunks():
        temp_file.write(chunk)
    temp_file.close()

store/templates/banners.html
{% block content %}

<div id="bannerCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="5000">
    <div class="carousel-inner banner-slide">
      <div class="carousel-item banner-slide active">
        <img src="/media/banners/banner_1.jpg" class="d-block w-100" alt="Баннер 1">
      </div>
      <div class="carousel-item banner-slide">
        <img src="/media/banners/banner_3.jpg" class="d-block w-100" alt="Баннер 2">
      </div>
    </div>
  
    <!-- Навигация для карусели (стрелки вперед/назад) -->
    <a class="carousel-control-prev" href="#bannerCarousel" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Предыдущий</span>
    </a>
    <a class="carousel-control-next" href="#bannerCarousel" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Следующий</span>
    </a>
</div>

{% endblock %}

  

store/templates/brand_detail.html
{% extends 'base.html' %}

{% block content %}

<html>
<head>
    <title>{{ brand.name }} - Детали бренда</title>
</head>
<body>
    <div class="row">
        <div class="col-lg-3" >
            {% if brand.image %}
                <img src="{{ brand.image.url }}" alt="{{ brand.name }} Image" class="img-fluid">
            {% endif %}
        </div>
        <div class="col-lg-9 text-center">
            <h4 style="text-shadow: 0px 2px 2px rgba(0, 0, 0, 0.2);">{{ brand.name }}</h4>
            <p>Страна происхождения: {{ brand.country }}</p>
            <p>{{ brand.description|safe }}</p>
        </div>
    </div>

    <h4 class="text-center">Товары бренда {{ brand.name }}:</h4>

    <div class="row" style="margin-left: -50px; margin-right: -50px; background-color: #F5F5F5;">
        {% for product in products %}
            <div class="col-lg-2 col-md-4 col-6 mb-4 mt-5">
                {% include 'product_card.html' %}
            </div>
        {% endfor %}
    
        <div class="pagination-container d-flex justify-content-center">
            <nav aria-label="Страницы">
                <ul class="pagination">
                    {% if products.has_previous %}
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page=1" aria-label="Первая страница"> << </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page={{ products.previous_page_number }}" aria-label="Предыдущая страница"> < </a>
                    </li>
                    {% endif %}

                    {% for page in products.paginator.page_range %}
                        <li class="page-item {% if page == products.number %}active{% endif %}">
                            <a class="page-link {% if page == products.number %}custom-active-page{% else %}text-custom-color {% endif %}" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endfor %}
                    
                    {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page={{ products.next_page_number }}" aria-label="Следующая страница"> > </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page={{ products.paginator.num_pages }}" aria-label="Последняя страница"> >> </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            </div>
    </div>
</body>
</html>
{% endblock %}

store/templates/brand_list.html
{% block content %}
<html>
<head>
    <title>Список брендов</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row justify-content-center"> 
            <div class="col-md-12 text-center"> 
                <h4>Наши бренды</h4>
            </div>
        </div>
        <div class="row">
            {% for brand in brands %}
                <div class="col-md-2 mb-4">
                    <a href="{% url 'brand_detail' brand.id %}" class="text-decoration-none text-dark">
                        {% if brand.image %}
                            <img src="{{ brand.image.url }}" alt="{{ brand.name }} Image" class="img-fluid">
                        {% endif %}
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>
{% endblock %}

store/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
<html>
<head>
    <title>{{ category.name }} - Детали категории</title>
</head>
<body>
    <div class="row">
        <div class="col-lg-3">
            {% if category.image %}
                <img src="{{ category.image.url }}" alt="{{ category.name }} Image" class="img-fluid">
            {% endif %}
        </div>
        <div class="col-lg-9 text-center" >
            <h4 style="text-shadow: 0px 2px 2px rgba(0, 0, 0, 0.2);">{{ category.name }}</h4>
            <p>{{ category.description|safe }}</p>
        </div>
    </div>
  

    {% if products %}
    <h4 class="text-center">Товары в категории {{ category.name }}:</h4>

    <div class="row" style="margin-left: -50px; margin-right: -50px; background-color: #F5F5F5;">
        {% for product in products %}
            <div class="col-lg-2 col-md-4 col-6 mb-4 mt-5">
                {% include 'product_card.html' %}
            </div>
        {% endfor %}
    
        <div class="pagination-container d-flex justify-content-center">
            <nav aria-label="Страницы">
                <ul class="pagination">
                    {% if products.has_previous %}
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page=1" aria-label="Первая страница"> << </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page={{ products.previous_page_number }}" aria-label="Предыдущая страница"> < </a>
                    </li>
                    {% endif %}

                    {% for page in products.paginator.page_range %}
                        <li class="page-item {% if page == products.number %}active{% endif %}">
                            <a class="page-link {% if page == products.number %}custom-active-page{% else %}text-custom-color {% endif %}" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endfor %}
                    
                    {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page={{ products.next_page_number }}" aria-label="Следующая страница"> > </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link text-custom-color" href="?page={{ products.paginator.num_pages }}" aria-label="Последняя страница"> >> </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    {% else %}
        <h4 class="text-center">В данной категории товаров нет</h4>
    {% endif %}
    
    
</body>
</html>
{% endblock %}

store/templates/category_list.html
{% block content %}
<html>
<head>
    <title>Список категорий</title>
</head>
<body>
<ul class="list-group d-inline-block float-left custom-shadow bg-body rounded w-100 rounded-0">
    {% for category in categories %}
        <li class="list-group-item text-wrap full-width" style="padding-left: 0; padding-right: 0; border: none;">
            {% if category.subcategories.exists %}
                <div class="accordion" id="categoryAccordion{{ category.id }}">
                    <a class="text-decoration-none category-link" style="color: #4B0082;" role="button" data-bs-toggle="collapse" href="#collapseCategory{{ category.id }}" aria-expanded="false" aria-controls="collapseCategory{{ category.id }}">
                        {{ category.name }}
                    </a>
                    <div id="collapseCategory{{ category.id }}" class="collapse" style="background-color: #F5F5F5;">
                        <div class="d-inline-block">
                            <ul class="list-group list-group-flush"> 
                                {% for subcategory in category.subcategories.all %}
                                    <li class="list-group-item"
                                    class="collapse" style="background-color: #F5F5F5;">
                                        <a href="{% url 'subcategory_detail' subcategory.slug %}" class="text-decoration-none" style="color: #4B0082;">
                                            {{ subcategory.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% else %}
                <a href="{% url 'category_detail' category.slug %}" class="text-decoration-none w-100 category-link" style="color: #4B0082;">
                    {{ category.name }}
                </a>
            {% endif %}
        </li>
    {% endfor %}
</ul>
</body>

</html>
{% endblock %}

store/templates/feedback_form.html
{% extends 'base.html' %}

{% block title %}Зворотній зв'язок{% endblock %}

<html>
<head>
    <title>Форма зворотнього зв'язку</title>
</head>
<body>
    {% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" class="custom-form" id="feedbackForm" action="{% url 'feedback' %}">
                {% csrf_token %}
                <div class="form-group"> 
                    <label for="id_name">Ваше ім'я:</label>
                    <input type="text" name="name" maxlength="100" required="" id="id_name" class="form-control">
                </div>
                <div class="form-group"> 
                    <label for="id_message">Повідомлення:</label>
                    <textarea name="message" required="" id="id_message" class="form-control"></textarea>
                </div>
                <div class="mt-3 button-container text-center">
                    <button type="submit" class="btn btn-custom shadow p-2">Надіслати</button>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>

store/templates/footer_category_list.html
{% load static %}

<footer style="background-color: #181818;">
    <div class="container-fluid">
        <h6 style="color: #FFFFFF; text-align: center; text-decoration: underline;">Все категории товаров</h6>

        <div class="category-grid" style="display: grid;
        grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
        gap: 10px;">
            {% for category in categories %}
            <div class="category-item" style="padding: 5px;">
                <a href="{% url 'category_detail' category.slug %}" class="text-decoration-none" style="color: #FFFFFF; text-decoration: none;">
                    {{ category.name }}
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <hr style="border-top: 1px solid #FF8C00; margin: 0;">
</footer>

store/templates/last_post.html
{% block content %}

<div class="container mt-4">
    <div class="row justify-content-center"> 
        <div class="col-md-12 text-center"> 
            <h4>Последние статьи</h4>
        </div>
    </div>
    <div class="row">
        {% for post in latest_posts %}
            {% if forloop.counter <= 3 %}
            <div class="col-md-4 mb-4">
                <div class="card article article_blog custom-shadow p-3 mb-5 bg-body rounded">
                    {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="card-img-top" style="height: 300px; object-fit: cover;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'post_detail' post.id %}" class="text-decoration-none text-custom-color">{{ post.title }}</a>
                        </h5>
                        <p class="card-text">{{ post.content|truncatechars:150|safe }}</p>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

store/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card custom-shadow p-3 mb-5 bg-body rounded" style="border-radius: 0% !important;">
        <div class="card-body">
          <h4 class="card-title text-center">Вход</h4>
          <form method="post">
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Имя пользователя:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Пароль:</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-custom shadow p-1 mb-3">Войти</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

store/templates/thank_you.html
{% extends 'base.html' %}

{% block content %}
<h1>Спасибо за ваш заказ!</h1>
<p>Мы ценим ваше доверие.</p>
{% endblock %}